const GET_GAMES = 'GET_GAMES'
const GET_GAME_DETAILS = 'GET_GAME_DETAILS'
const GET_SEARCHED = 'GET_SEARCHED'
const CLEAR_SEARCHED = 'CLEAR_SEARCHED'

const START_LOADING = 'START_LOADING'
const DONE_LOADING = 'DONE_LOADING'

export {
  START_LOADING,
  DONE_LOADING,
  GET_GAMES,
  GET_GAME_DETAILS,
  GET_SEARCHED,
  CLEAR_SEARCHED,
}
