const GET_GAMES = 'GET_GAMES'
const GET_GAME_DETAILS = 'GET_GAME_DETAILS'

const START_LOADING = 'START_LOADING'
const DONE_LOADING = 'DONE_LOADING'

export { START_LOADING, DONE_LOADING, GET_GAMES, GET_GAME_DETAILS }
